version: "3.8"
services:
  web:
    build: .
    # network_mode: host   # Uncomment for Linux host mode
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_LOCK_DIR=/var/lock/apache2
      - APACHE_SERVER_NAME=localhost
